server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: serie-service-parcial
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/serie
      database: serie
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  zipkin:
    base-url: http://localhost:9411/
    enabled: true    
