server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: serie-service-parcial
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: Series
      port: 27017
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  zipkin:
    base-url: http://localhost:9411/
    enabled: true    
